Use a simple type for ServiceTier (#61)
Fix for arbitrary service tiers provided by various model providers. 



E.g. 

* OpenAI has `'flex'` which is not supported right now.
* Groq defaults to `'on_demand'`, which causes the following exception:

```
Exception: DecodeFailure "Error in $['service_tier']: parsing OpenAI.V1.Chat.Completions.ServiceTier failed, expected one of the tags [\"default\"], but found tag \"on_demand\""
```